### ISSUE TITLE
HistogramReadlength and log transformation in BAM file uncorrect?

### ISSUE THREAD

**Issue by FiniDG-HAN** [wdecoster/NanoPlot#108]
I see that the read length distribution of both files do not agree with each other? In the LogTransformed file the most reads are around 20k and in the normal file most reads are around 5k. But if you look at Weighted file, it seems to be around 20k again? Does this have to do with clipped/mapped reads or something? Because if I use the fasta file both have the highest peak at 5k. I was told that this peak in the fasta is sometimes made on purpose during the library prep?

### bam
![histogramreadlength](https://user-images.githubusercontent.com/31845711/48608363-bcf51a00-e982-11e8-9c16-dcaef8412eb9.png)
![logtransformed_histogramreadlength](https://user-images.githubusercontent.com/31845711/48608384-c1213780-e982-11e8-9a65-90492a4182c3.png)
![weighted_histogramreadlength](https://user-images.githubusercontent.com/31845711/48608396-c4b4be80-e982-11e8-9970-868561182fe0.png)

### fasta
![histogramreadlength](https://user-images.githubusercontent.com/31845711/48608437-d0a08080-e982-11e8-94b7-0e44c1feb86a.png)
![logtransformed_histogramreadlength](https://user-images.githubusercontent.com/31845711/48608446-d39b7100-e982-11e8-8a07-4b1670e3e717.png)

**Comment by wdecoster** [comment]
> In the LogTransformed file the most reads are around 20k and in the normal file most reads are around 5k.

In the 'normal' file every bin is 100 bases, but that is not the case in the log-transformed plot. As you can see in the log-transformed plot the distance between 100 and 1000 bases on the x-axis is the same as between 10000 and 100000. Exactly because of this log transformation, you can see the long reads better because they get clumped together. Direct comparison of 'normal' and log transformation doesn't really make sense. Nanopore reads have a long-tailed distribution, making the longest reads hard to see in an untransformed plot as you can see in the 'normal' plots.

> But if you look at Weighted file, it seems to be around 20k again?

For the weighted histogram, a read of 20kb will contribute 10x more than a read of 2kb - and as such explaining again why the peak is different. It shows you were the most _bases_ are, not the most _reads_.

Note that in the plot of the fasta file you see a peak at 3.8kb (if I remember correctly) corresponding to the lambda control DNA fragment (DCS). You don't see that in the bam since it is not aligned.

> I was told that this peak in the fasta is sometimes made on purpose during the library prep?

That depends on library prep methods (shearing and size selection).

**Comment by FiniDG-HAN** [comment]
Thank you for your detailed explanation!, especially the first part. I now know that the 3.8 kb (or something else around 5 kb) is called a lambda spike-in. I think that you are familiar with it, because you talk about the lambda control fragment. Do you know if it is possible to remove these "fake" reads from your fasta/fastq? 
I know this is not the scope of NanoPlot, but I am using these reads to simulate new reads, and this "fake" peak is affecting the simulation, so that the simulated reads also have this peak, but those reads actually map. I thought maybe you could help me along the way?

**Comment by wdecoster** [comment]
Yes, it's the lambda control fragment, a 3' part of the lambda genome which is used as internal control.

You can remove them using my [NanoLyse](https://github.com/wdecoster/nanolyse) tool.

**Comment by FiniDG-HAN** [comment]
Thank you very much :)
