### ISSUE TITLE
Add axis labels to dynamic histogram read length plot

### ISSUE THREAD

**Issue by axgraf** [wdecoster/NanoPlot#159]
Would it be possible to add axis labels to the dynamic histogram read length plot. I think it shows not the number of reads, thus only the percent identity, correct?
Thank you

**Comment by wdecoster** [comment]
No worries, I transferred the issue. Those are read lengths yes, why did you mention percent identity?

**Comment by axgraf** [comment]
Just assumed it from your code: https://github.com/wdecoster/NanoPlot/blob/6330111128aad6ee3836d57b7bf314b39003d329/nanoplot/NanoPlot.py#L314
More specially the data frame: `datadf["percentIdentity"]`
Might be wrong, that is why I raised the issue ;-).
I first also thought it should be read length. In the first line of the report it shows me roughly 6 Mio. reads (number of reads: 5,853,937.0). I assume then, that the x-axis should show the read length and the y-axis the number of reads falling in that bin. With that assumption the bars in the histogram will not sum up to my number of input reads. So I'm not really sure what I'm looking at. Maybe I missed something!?
By the way I really like this kind of dynamic version of the plot, with that neat zooming option!!!

**Comment by wdecoster** [comment]
That line from my code is under an if statement https://github.com/wdecoster/NanoPlot/blob/6330111128aad6ee3836d57b7bf314b39003d329/nanoplot/NanoPlot.py#L265
The code will only run when there is percent identity in your dataframe, which you can only get from a bam/cram file.

The code for the plot you are asking about is hidden somewhere deeper: https://github.com/wdecoster/NanoPlot/blob/6330111128aad6ee3836d57b7bf314b39003d329/nanoplotter/nanoplotter_main.py#L335
I kinda forgot, but what it does is also downsampling of the reads to a maximum of 10000 reads. Otherwise, the plot is too large and takes too much space (gigabytes) in the report.
And that explains that the Y-axis doesn't match. The X-axis is definitely read lengths.

I should clarify that...

**Comment by wdecoster** [comment]
And now fixed in v1.28.1 (on PyPI, and soon on conda.)

**Comment by axgraf** [comment]
Great! Thank you! I will try it right away!
