### ISSUE TITLE
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

### ISSUE THREAD

**Issue by sagrudd** [wdecoster/NanoPlot#181]
Morning Wouter,

I have this simple snippet of error from a Snakefile (pipeline_structural_variation) - a user is exploring structural variation with large PromethION datasets.

Do you have any thoughts here - I appreciate that the content here is minimal but I don't have the dataset and have not seen this error myself; would appreciate any thoughts you may have?

```
  File "/home/prom/miniconda3/envs/pipeline-structural-variation/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

If you read this then NanoPlot 1.29.1 has crashed :-(
Please try updating NanoPlot and see if that helps...
```

**Comment by wdecoster** [comment]
Hi sagrudd,

NanoPlot uses multiprocessing to run the extraction of information in multiple threads simultaneously, but that requires that the information is passed back to the main thread afterward for plotting and statistics. If that dataset gets too large then this error is what you get. I assume the pipeline uses NanoPlot on a single rather large bam file? For bam files NanoPlot uses two levels of parallelization: once per file and once per chromosome. If this is indeed one large bam file then NanoPlot can be executed with `--huge`, as this will bypass the per-file parallelization (which is obsolete here since you only have one file) and only split per chromosome (of which the datasets hopefully should be small enough to be passed back to the main thread).

That said, all of that could possibly be improved, and if `--huge` doesn't solve this or doesn't work in your case because you have multiple bam files at the same time for one NanoPlot command then I can look into alternative solutions.

Cheers,
Wouter

**Comment by sagrudd** [comment]
Fabulous, thanks for the update! I'll give this a go and will comment further in due course.

**Comment by wdecoster** [comment]
Please let me know if you encounter further issues!
