### ISSUE TITLE
_imaging.cpython-37m-x86_64-linux-gnu.so: cannot open shared object file

### ISSUE THREAD

**Issue by wdecoster** [wdecoster/NanoPlot#205]
Issue reported by @David-Lee86, copied from older issue: https://github.com/wdecoster/NanoPlot/issues/122#issuecomment-691568649

> Hi, I installed nanoplot with "pip3 install NanoPlot". However when I try to run it, I am getting the following error
> 
> /software/imaging/miniconda3/lib/python3.7/site-packages/matplotlib/backend_bases.py:57: DeprecationWarning: PILLOW_VERSION is deprecated and will be removed in a future release. Use version instead.
> from PIL import PILLOW_VERSION
> Traceback (most recent call last):
> File "/gpfs01/home/sbadg3/.local/bin/NanoPlot", line 5, in
> from nanoplot.NanoPlot import main
> File "/gpfs01/home/sbadg3/.local/lib/python3.7/site-packages/nanoplot/NanoPlot.py", line 20, in
> import nanoplot.utils as utils
> File "/gpfs01/home/sbadg3/.local/lib/python3.7/site-packages/nanoplot/utils.py", line 11, in
> import matplotlib.pyplot as plt
> File "/software/imaging/miniconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2355, in
> switch_backend(rcParams["backend"])
> File "/software/imaging/miniconda3/lib/python3.7/site-packages/matplotlib/init.py", line 832, in getitem
> plt.switch_backend(rcsetup._auto_backend_sentinel)
> File "/software/imaging/miniconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 213, in switch_backend
> switch_backend("agg")
> File "/software/imaging/miniconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 221, in switch_backend
> backend_mod = importlib.import_module(backend_name)
> File "/gpfs01/software/imaging/miniconda3/lib/python3.7/importlib/init.py", line 127, in import_module
> return _bootstrap._gcd_import(name[level:], package, level)
> File "/software/imaging/miniconda3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 45, in
> from PIL import Image
> File "/software/imaging/miniconda3/lib/python3.7/site-packages/PIL/Image.py", line 93, in
> from . import _imaging as core
> ImportError: /software/imaging/miniconda3/lib/python3.7/site-packages/PIL/_imaging.cpython-37m-x86_64-linux-gnu.so: cannot open shared object file: Permission denied
> 
> Please help

**Comment by wdecoster** [comment]
Does `/software/imaging/miniconda3/lib/python3.7/site-packages/PIL/_imaging.cpython-37m-x86_64-linux-gnu.so` exist? If so, what are the permission on this file?

**Comment by David-Lee86** [comment]
Hi, sorry for not starting this issue in a new thread. The file does exist and has the following status:

-rwxr-x--x 1 mszss8 ui-hpcimaging 640656 May 26 11:55 _imaging.cpython-37m-x86_64-linux-gnu.so

**Comment by wdecoster** [comment]
That looks weird. You have permission to execute it (x) but not read or write?

Could we try another way of installing? Please try `pip3 uninstall NanoPlot` and install with conda in a new environment:
```
conda create -n nanoplot  -c bioconda nanoplot
conda activate nanoplot
```

**Comment by David-Lee86** [comment]
Thanks for the comments. I'm trying to run NanoPlot on a HPC. I don't have admin privileges, so I don't know if this might be the cause of the issue. I ran the codes as you suggested and the installation process went smoothly, however when I tried to use the software I'm still getting the error (see below).

pip3 uninstall NanoPlot
conda create -n nanoplot  -c bioconda nanoplot
conda activate nanoplot
NanoPlot --help


/gpfs01/home/sbadg3/.local/lib/python3.7/site-packages/nanomath/nanomath.py:132: DeprecationWarning: Call to deprecated function errs_tab.
  def ave_qual(quals, qround=False, tab=errs_tab(128)):
/software/imaging/miniconda3/lib/python3.7/site-packages/nbformat/notebooknode.py:4: DeprecationWarning:

Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working

/software/imaging/miniconda3/lib/python3.7/site-packages/matplotlib/backend_bases.py:57: DeprecationWarning:

PILLOW_VERSION is deprecated and will be removed in a future release. Use __version__ instead.

Traceback (most recent call last):
  File "/gpfs01/home/sbadg3/.conda/envs/SBG_NANOPLOT/bin/NanoPlot", line 6, in <module>
    from nanoplot.NanoPlot import main
  File "/gpfs01/home/sbadg3/.conda/envs/SBG_NANOPLOT/lib/python3.7/site-packages/nanoplot/NanoPlot.py", line 24, in <module>
    import nanoplotter
  File "/gpfs01/home/sbadg3/.conda/envs/SBG_NANOPLOT/lib/python3.7/site-packages/nanoplotter/__init__.py", line 1, in <module>
    from .nanoplotter_main import *
  File "/gpfs01/home/sbadg3/.conda/envs/SBG_NANOPLOT/lib/python3.7/site-packages/nanoplotter/nanoplotter_main.py", line 35, in <module>
    import matplotlib.pyplot as plt
  File "/software/imaging/miniconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2355, in <module>
    switch_backend(rcParams["backend"])
  File "/software/imaging/miniconda3/lib/python3.7/site-packages/matplotlib/pyplot.py", line 221, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/gpfs01/home/sbadg3/.conda/envs/SBG_NANOPLOT/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/software/imaging/miniconda3/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 45, in <module>
    from PIL import Image
  File "/software/imaging/miniconda3/lib/python3.7/site-packages/PIL/Image.py", line 93, in <module>
    from . import _imaging as core
ImportError: /software/imaging/miniconda3/lib/python3.7/site-packages/PIL/_imaging.cpython-37m-x86_64-linux-gnu.so: cannot open shared object file: Permission denied

**Comment by wdecoster** [comment]
Could you try to install pillow also with conda?

`conda install -c anaconda pillow`

**Comment by David-Lee86** [comment]
Hi, thanks for the comment. I did the following, however I'm still getting the error

conda create -n anaconda_pillow -c anaconda pillow
conda activate nanoplot
conda activate --stack anaconda_pillow
NanoPlot --help

**Comment by wdecoster** [comment]
To be honest I have no idea at all what's going on here.
