### ISSUE TITLE
Running on rebasecalled reads including methylation information

### ISSUE THREAD

**Issue by smf96** [wdecoster/NanoPlot#300]
Hello,

I have recently rebasecalled my data with the latest guppy including CpG methylation calling and I was wondering if nanoplot can be run on the output?

I have tried running it on the unaligned bams that guppy produces but get this error:

![image](https://user-images.githubusercontent.com/52749489/178550665-fcb3f333-2ff6-4b1b-ab72-a01875518cfb.png)

I also extract the fastqs from the unaligned bams and transfer over the modification information with 
```samtools fastq -T Mm,Ml sample1.bam > sample1.fq```
but I am getting this error when I try run nanoplot on those fastq:
![image](https://user-images.githubusercontent.com/52749489/178550581-b2d72c0a-0480-4c56-9988-3a2db1bbc4a7.png)

Any help is much appreciated, thank you!

All the best,

Sarah

**Comment by wdecoster** [comment]
Hi Sarah,

How did you run NanoPlot for both errors? Did you see there is an --ubam option for unaligned bams?
And did you use --fastq_rich for the fastqs? Because that option expects some more structure in the fastq identifier with regard to time and channel, which is not present in yours. It should work with just --fastq though.

Wouter

**Comment by smf96** [comment]
Hello Wouter,

Those worked perfectly, cheers!

**Comment by wdecoster** [comment]
Good to hear!
