### ISSUE TITLE
NanoPlot: error: arguments required + command not found

### ISSUE THREAD

**Issue by ccerpas** [wdecoster/NanoPlot#301]
Hi
I can not use nanoplot to run my sequences QC.  After installed with conda, I received this massage 
NanoPlot: error: one of the arguments --fastq --fasta --fastq_rich --fastq_minimal --summary --bam --ubam --cram --pickle --feather is required
I updated using:
pip install NanoPlot –upgrade
and got this;
Successfully uninstalled NanoPlot-1.32.1
Successfully installed NanoPlot-1.40.0 Python-Deprecated-1.1.0 kaleido-0.2.1
but I got the same deal
then I tried
conda update nanoplot

when I run my QC I received the next message:
nanoplot: command not found

Thanks for any help you can give me, I'm a newbie at this.

**Comment by wdecoster** [comment]
Hi,

Please add the commands that you tried.

Wouter

**Comment by ccerpas** [comment]
Hi, thanks for your quick answer. 
I used
conda create --name nanoplot
conda update -n base -c defaults conda
conda activate nanoplot
conda install -c biconda nanoplot
at this point I get the next message:
Collecting package metadata (current_repodata.json): failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: biconda
  channel url: https://conda.anaconda.org/biconda
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.

I ran those last two without changing anything (there was no option), configuration was  - defaults and the sources shows nothing

then NanoPlot  with no good results (command not found)
then I tried with
conda install -c bioconda/label/cf201901 nanoplot
but also fails  solving the environments

**Comment by wdecoster** [comment]
> conda install -c biconda nanoplot

It's bioconda. not biconda.


Try this:
```
conda create -n nanoplot nanoplot
conda activate nanoplot
NanoPlot -h
```

**Comment by ccerpas** [comment]
Hi, I'm still having the problem
when I run the NanoPlot -h  command  everything looks fine, but then, when I run the nanoplot analysis I'm still having the argument require error than I mentioned before.

**Comment by wdecoster** [comment]
I can't help you if you don't share the command you tried.

**Comment by lucyintheskyzzz** [comment]
Hi I am getting the same error message, which is weird because I used the same code I used a few days ago:

#!/bin/bash
#SBATCH -A loni_virus2023    ### Allocation name
#SBATCH -p single ## queue name
#SBATCH -t 2:00:00 ## wall time
#SBATCH -N 1 ## number of nodes
##SBATCH -n 16 ## number of tasks
##SBATCH -c 47 ## number of cores per task
#SBATCH -o nanoplot.out ## standard output file
#SBATCH -e nanoplot.err ## standard error file
#SBATCH --mail-type FAIL
#SBATCH --mail-type BEGIN
#SBATCH --mail-type END
#SBATCH --mail-user kvigil@tulane.edu
#SBATCH -J nanoplot_seawater ## job name

##activate conda
source /usr/local/packages/python/3.9.7-anaconda/etc/profile.d/conda.sh


# Load the Nanoplot module
conda activate nanoplot-env

##NanoPlot 1.32.1 version

# Define the directory containing FASTQ files
fastq_dir="/work/kvigil/ONR020124_oyster/concatenate/concatenate"

# Define the output directory for Nanoplot results
output_dir="${fastq_dir}/nanoplot_results"

# Create the Nanoplot results directory if it doesn't exist
mkdir -p "$output_dir"

# Iterate over all FASTQ files in the directory
for fastq_file in "${fastq_dir}"/*.fastq.gz; do
    # Check if the current file is a regular file
    if [[ -f "$fastq_file" ]]; then
        # Run Nanoplot on the current FASTQ file
        NanoPlot -t 48 -o "${output_dir}/$(basename ${fastq_file%.fastq.gz})" "$fastq_file"
    fi
done




error message from log file: 
usage: NanoPlot [-h] [-v] [-t THREADS] [--verbose] [--store] [--raw] [--huge]
                [-o OUTDIR] [-p PREFIX] [--tsv_stats] [--maxlength N]
                [--minlength N] [--drop_outliers] [--downsample N]
                [--loglength] [--percentqual] [--alength] [--minqual N]
                [--runtime_until N] [--readtype {1D,2D,1D2}] [--barcoded]
                [--no_supplementary] [-c COLOR] [-cm COLORMAP]
                [-f {eps,jpeg,jpg,pdf,pgf,png,ps,raw,rgba,svg,svgz,tif,tiff}]
                [--plots [{kde,hex,dot,pauvre} [{kde,hex,dot,pauvre} ...]]]
                [--listcolors] [--listcolormaps] [--no-N50] [--N50]
                [--title TITLE] [--font_scale FONT_SCALE] [--dpi DPI]
                [--hide_stats]
                (--fastq file [file ...] | --fasta file [file ...] | --fastq_rich file [file ...] | --fastq_minimal file [file ...] | --summary file [file ...] | --bam file [file ...] | --ubam file [file ...] | --cram file [file ...] | --pickle pickle | --feather file [file ...])
NanoPlot: error: one of the arguments --fastq --fasta --fastq_rich --fastq_minimal --summary --bam --ubam --cram --pickle --feather is required

**Comment by wdecoster** [comment]
NanoPlot: error: one of the arguments --fastq --fasta --fastq_rich --fastq_minimal --summary --bam --ubam --cram --pickle --feather is required
