### ISSUE TITLE
Nanoplot iterations produce different outputs 

### ISSUE THREAD

**Issue by ASTR44** [wdecoster/NanoPlot#339]
Hi,

I have noticed that the output fra Nanoplot differs between iterations. The numbers in the summary statistics are the same but the plots look different. Here are 5 examples all made with the same command: 
`NanoPlot --fastq_rich Ec001_super.fastq.gz --N50 -o Ec001_super_nanoplot5`

![1_LengthvsQualityScatterPlot_dot](https://github.com/wdecoster/NanoPlot/assets/122440360/d721cad9-e95a-44a3-b913-27abd514f732)
![2_LengthvsQualityScatterPlot_dot](https://github.com/wdecoster/NanoPlot/assets/122440360/d8e7dfd2-13d9-4383-b43b-f7b1579695a4)
![3_LengthvsQualityScatterPlot_dot](https://github.com/wdecoster/NanoPlot/assets/122440360/4cd8e883-3163-498d-8aa7-13ac2d6f39d9)
![4_LengthvsQualityScatterPlot_dot](https://github.com/wdecoster/NanoPlot/assets/122440360/32117ccb-1a93-4537-8de6-3a429c00a208)
![5_LengthvsQualityScatterPlot_dot](https://github.com/wdecoster/NanoPlot/assets/122440360/d7c3c598-1615-4422-89fe-3bdf16da48bb)

**Comment by wdecoster** [comment]
Yes, that is expected behavior. The plotting function will randomly sample up to 10000 reads for the plot (https://github.com/wdecoster/NanoPlot/blob/master/nanoplotter/nanoplotter_main.py#L107). This is mainly for the speed of plotting and disk size of the plots. It may lead to subtle differences in outliers, but should not affect the bulk of your data.


Hope that helps!

**Comment by ASTR44** [comment]
Okay, then it makes sense :) Thank you for the quick reply!

**Comment by ASTR44** [comment]
Okay, then it makes sense :) Thank you for the quick reply!
