### ISSUE TITLE
width of bivariate plots should be identical to the width of other plots

### ISSUE THREAD

**Issue by tolot27** [wdecoster/NanoPlot#39]
The size of bivariate plots is larger than that of the other plots. If the plots are combined into one single file (i.e. in case of PDF with pdfunite), it would be good, if they would have the same size.

**Comment by wdecoster** [comment]
You mean you are combining the generated image files (png/jpeg/...) in a pdf file?

Note that there is also an html summary containing all stats and images, but images may not have the same size in that too.

**Comment by tolot27** [comment]
Yes, I'm combining some of the generated pdf graphics into one pdf file. I'm aware of the html report but it contains more graphics than needed and no svgs, only bitmap graphics.

I also thought about creating an issue for requesting a parameter to combine pdfs and also for specifying which "normal" (non bivariate) plots should be created.

**Comment by wdecoster** [comment]
Do you want the same width for each image?

Since not all plots are square it wouldn't be trivial to create plots of the same size (width and height). I just checked briefly, and it looks like the TimeLengthViolinPlot and TimeQualityViolinPlot also have a size different from the rest, but perhaps those are not the plots you are looking for.

I have to think about what's the best way to handle your request, but currently, I'm thinking the easiest would be to have a separate script for resizing the output, prior to creating a pdf. Would that work for you?

**Comment by tolot27** [comment]
> Do you want the same width for each image?

Yes, same width would be sufficient. Same height is not necessary at all. I'll change the title of the issue accordingly.

Setting the same width in python is preferable than resizing the output with a script. Mostly ghostscript whould be necessary for that.

**Comment by wdecoster** [comment]
You mentioned you are working with svg images. I've been using Python for [resizing and combining svg images](https://gigabaseorgigabyte.wordpress.com/2017/11/15/resizing-and-combining-multiple-svg-images/) before, so I have some ideas on how to handle this.

Currently, "at plot creation" I don't specify anything about the sizes, and essentially leave this to the downstream seaborn and matplotlib modules. That's why it would be easier for me to have another Python script adjust widths afterwards.

But perhaps I should think a bit longer about this.

Wouter

**Comment by wdecoster** [comment]
I adapted some code and wrote a "helper" script to take care of resizing svg images, please have a look at https://github.com/wdecoster/combine_images
If you have problems/feedback/suggestions please open an issue in that repository.

Sorry, I'm not going to modify NanoPlot itself for this (too much trouble).

Cheers,
Wouter
