### ISSUE TITLE
Summary stats feature request

### ISSUE THREAD

**Issue by AnjuniPeiris** [wdecoster/NanoPlot#50]
Hi, would it be possible to get the summary stats to show the number of reads mapped, the number of bases mapped, and how many bases the reads cover?
Thanks!

**Comment by wdecoster** [comment]
Hi AnjuniPeiris,

When using NanoPlot with --bam I get (among other things):
```
Number of reads:        629618
Total bases:    3640855938
Total bases aligned:    3101875541
```

That number of reads are aligned reads in this case.

I agree it would make sense to also add the total number of reads there. I'll think about that, because how I currently setup the functions it's not trivial.

You also ask for "how many bases the reads cover". Here you mean the span of the reads on the reference genome, taking indels into account? That sounds tricky :-)

**Comment by AnjuniPeiris** [comment]
Thanks for that! Yep, for "how many bases the reads cover", I meant how much of the reference genome is covered by the reads, taking indels into account, if it's possible to get that number.

**Comment by wdecoster** [comment]
Okay, I think that should be possible. I've put it on my to-do list and will leave this issue open for now. I'm quite busy so it could take a while, unfortunately.

**Comment by PGTB33** [comment]
Hi wdecoster,

I would like tu run NanoPlot on guppy summaries. To do so I've arranged the columns of the guppy summary to fit with 1D ( by adding a fake num_called_template column), but it does not work, see log below. I've set filtering parameters to discard reads with a length lower than 500bp and with qual < 9. It seems that the length filtering discard all reads. Is there a way ro tun nanoplot on guppy summaries ?

Thanks,

Charlotte


2018-03-13 10:03:38,186 Calculated statistics
2018-03-13 10:03:38,186 Using sequenced read lengths for plotting.
2018-03-13 10:03:38,187 Removed 49999 reads shorter than Nonebp.
2018-03-13 10:03:38,189 Removing 0 reads with quality below Q9.
2018-03-13 10:03:38,189 Processed the reads, optionally filtered. 0 reads left
2018-03-13 10:03:38,189 Nanoplotter: Valid color #4CB391.
2018-03-13 10:03:38,190 index 0 is out of bounds for axis 0 with size 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nanoplot/NanoPlot.py", line 85, in main
    plots = make_plots(datadf, settings)
  File "/usr/local/lib/python3.5/dist-packages/nanoplot/NanoPlot.py", line 318, in make_plots
    n50 = nanomath.get_N50(np.sort(datadf["lengths"]))
  File "/usr/local/lib/python3.5/dist-packages/nanomath/nanomath.py", line 34, in get_N50
    return readlengths[np.where(np.cumsum(readlengths) >= 0.5 * np.sum(readlengths))[0][0]]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by wdecoster** [comment]
Hi AnjuniPeiris,

For an unrelated project, I checked the[ insertion-deletion ratio in nanopore reads](https://gigabaseorgigabyte.wordpress.com/2018/03/16/insertion-deletion-ratio-in-oxford-nanopore-promethion-data/) last week. Since this ratio is approximately 1, I believe the "how many bases the reads cover" to be roughly similar to the read length itself, so I don't really see the point in adding another option for that.

Cheers,
Wouter
