### ISSUE TITLE
Question about concatenating multiple summary files

### ISSUE THREAD

**Issue by shenuhcide** [wdecoster/NanoPlot#60]
We are restarting our sequencing run on the same flow cell and thus have multiple sequence summary files from one flow cell after basecalling on abacore. Is it possible to take that into account and plot the quality over time in terms of absolute time or hours since the time stamp of the first run? 

If not, how would you recommend I concatenate multiple sequence summary files and amend the table to achieve a true quality over time plot?

**Comment by wdecoster** [comment]
Hi shenuhcide,

NanoPlot can take multiple summary files simulatenously, e.g.:

    NanoPlot --summary file1.txt file2.txt file3.txt

But do you mean the start_time column in your file2 starts again at 0, and as such the plots are not correctly produced? I'm not sure when the start_time gets reset by MINknow, since I never use it for basecalling.

If so, the easiest way would be to use the `--fastq_rich` input option, which will also extract time information from the minknow/albacore/guppy fastq format, e.g.:

    NanoPlot --fastq_rich reads1.fastq.gz reads2.fastq.gz

Compression of the reads is optional. Admittedly, extracting information from fastq files is a bit slower than using summaries.

Please let me know if this works for you.

Cheers,
Wouter

**Comment by wdecoster** [comment]
Hi Sheina,

Yes, I think that would roughly be accurate, although I haven't done anything like that before. It's not exactly correct because between the last read of summary1 and the first read of summary2 there was some time, but that's probably negligible and won't influence plots that much.
Note that another solution would be to repeat the basecalling with albacore ;-)

Cheers,
Wouter

**Comment by shenuhcide** [comment]
I amended my sequencing_summary.txt files accordingly and got the desired output. Thanks! Repeating the basecalling with albacore was not an option, it takes too long.

Cheers,
Sheina

**Comment by wdecoster** [comment]
Thanks for the feedback!
