### ISSUE TITLE
suggestion: filtering albacore summary file

### ISSUE THREAD

**Issue by jvolkening** [wdecoster/NanoPlot#62]
When taking an albacore summary file as input, you might considering filtering out reads that fail quality filtering (the `passes_filtering` column). This could be optional but should probably be the default, since it will reflect the reads actually written to the 'pass' directory by albacore and what a user would get if they fed that FASTQ file into NanoPlot directly.

**Comment by wdecoster** [comment]
Hi jvolkening,

Thank you for the suggestion. We usually turn of the splitting of reads in two groups by albacore. I think it really depends on your application whether this cut off makes any sense or not. Probably for assembly, SNP calling, diagnostics you don't want the most terrible reads, but for example for structural variants I don't mind getting evidence from lower quality reads.

Note that there is a `--minqual` flag in NanoPlot, which you could use to set your prefered cut off. I don't like setting 7 as the default here, because it's unexpected behaviour. If you present a summary file to NanoPlot each read will get plotted, unless you explicitly set the parameter to do that differently.

Cheers,
Wouter

**Comment by jvolkening** [comment]
To be honest, I didn't realize that the albacore filtering was a simple hard-coded quality cutoff. Indeed, `--minqual 7` fits the bill.

Thanks for the enlightenment,
Jeremy
