### ISSUE TITLE
Min sequence length data

### ISSUE THREAD

**Issue by laurafisch9** [wdecoster/NanoPlot#73]
Is there anyway to get stats about the shortest reads and their average quality score?
I would like more details on sequencing lenghts

**Comment by wdecoster** [comment]
Can you elaborate on which output you are aiming for?

Note that you can set a `--maxlength` filter. When filtering two NanoStats reports will be created, one before (full dataset) and one after filtering.

**Comment by laurafisch9** [comment]
This --maxlenght filter looks promising but I cannot get it to work

Below is the command I used

~/.local/bin/NanoPlot -t 10 --fastq porechop_FN58_all_reads.fastq --maxlength 40000 -o porechop_nanoplot_complete


Here is there error 
ValueError: Lengths of sequence and quality values differs  for d229af00-6e57-4dcf-9d01-cdd3836e02b7 runid=3fa69d516408a3647b522e812796d708fd667635 read=4312 ch=91 start_time=2018-04-17T15:03:21Z (5542 and 3095).

Attached is the log file
[NanoPlot_20180621_1126.log](https://github.com/wdecoster/NanoPlot/files/2124323/NanoPlot_20180621_1126.log)

**Comment by wdecoster** [comment]
That error is coming from Biopython, the module I use for parsing fastq files. It reports that your fastq file is likely corrupted because there is a difference between the length of the sequence string and the quality string, for read `d229af00-6e57-4dcf-9d01-cdd3836e02b7`.

You can take a look at that read to verify this:

`grep -A7 -B4 d229af00-6e57-4dcf-9d01-cdd3836e02b7 porechop_FN58_all_reads.fastq`

Which will print out the corrupt read and the one before and after it to compare with.

You may have to repeat the process which gave you this fastq, something went wrong there. Note that NanoPlot can also use compressed data (e.g. gzip) so you don't have to keep the fastq uncompressed.

**Comment by laurafisch9** [comment]
Other tools also use compressed data. 
Am I supposed to compress the data output from the fast5 basecaller (we are using albacore) 
Do you know if albacore will give me a fastq.gz file if I specify that output?

**Comment by wdecoster** [comment]
No, as far as I know, albacore will give you an uncompressed fastq file.
You can compress this file as below:

`gzip porechop_FN58_all_reads.fastq` 

which will create `porechop_FN58_all_reads.fastq.gz`

**Comment by laurafisch9** [comment]
Can you tell me what the -A7 -B4 option are for in the above command with grep?

**Comment by wdecoster** [comment]
The `-A` argument specifies the number of lines printed **a**fter the pattern is found (7: give me the 3 lines of the corrupt fastq record and the 4 lines of the next record). The `-B` argument specifies the number of lines printed **b**efore  the pattern is found (4, because I want the fastq record before the corrupt one).

**Comment by laurafisch9** [comment]
Ahhh ok that makes sense to me. 
From poking around on nanopore's community it sounds like I am not the only one who has received this error message. Do you know why a fastq file might become corrupted?

**Comment by wdecoster** [comment]
Presumably, the process which you used before crashed. Is the corrupt read the last one in the file?

**Comment by laurafisch9** [comment]
Ok! I am reruning the process. It looks like the corrupted sequence is indeed the last sequence in the file

**Comment by laurafisch9** [comment]
everytime I try to use the `--maxlenght` I get the following error no matter if is use a .fastq or fastq.gz file
`NanoPlot: error: unrecognized arguments: --maxlenght 40000`

**Comment by laurafisch9** [comment]
ahhh yes. Correcting that type worked. Thank you very much! and the corrupt file issue is also being resolved.

**Comment by wdecoster** [comment]
Great, so can I consider this issue as solved or do you have further questions?

**Comment by laurafisch9** [comment]
You can consider it solved. Thanks again!
