### ISSUE TITLE
just html report

### ISSUE THREAD

**Issue by tolot27** [wdecoster/NanoPlot#95]
It would be nice to just create the HTML report without any other image files.

**Comment by wdecoster** [comment]
I think it would be possible, with the exception of the pauvre plot. For the others the html is generated based on the fig object (I can walk you through this in more detail if you like), but for pauvre I use the image (because I do not have access to that fig object).

What would be the advantage? If the report is all you need, indeed the images are not necessary and can be deleted to save a bit of disk space. I don't expect it would save a lot of time, though.

**Comment by wdecoster** [comment]
I'm not planning on implementing this, but if there are more people interested I may change my mind.
